DROP TABLE IF EXISTS book;
CREATE TABLE book (id INTEGER NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id));
DROP TABLE IF EXISTS user;
CREATE TABLE user (id INTEGER NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, PRIMARY KEY(id));
INSERT INTO user (username, password, salt) VALUES ("dave", "W21P/Z6cQY/x2NK8ahQzsy0l3h1l4DXojShH1n7+lGA0lhekHOxChCZWbgduVonIV9oxKUkdpdWXswvcHOF2Mw==", "");
DROP TABLE IF EXISTS user_book;
CREATE TABLE user_book (user_id INTEGER NOT NULL, book_id INTEGER NOT NULL, PRIMARY KEY(user_id, book_id));
CREATE INDEX IDX_B164EFF8A76ED395 ON user_book (user_id);
CREATE INDEX IDX_B164EFF816A2B381 ON user_book (book_id);
